### ISSUE TITLE
Auto Updating

### ISSUE THREAD

**Issue by Bigben83** [csenkbeil/EnergyDashboard#1]
Hi csenkbeil

Is there anyway this could automatically update from the xls sheet showing on the Aurora Website
http://www.hydro.com.au/system/files/water-storage/storage_summary-4.xls

**Comment by csenkbeil** [comment]
Excellent Idea, I'll look into it. The dashboard is a static site and I'll keep it that way, but I will look at writing a tool to automatically modify the datasource, possible as a datafile in an S3 bucket on AWS.

**Comment by csenkbeil** [comment]
Hi @Bigben83 

Hydro have a dam level widget on their website now for public updates, and the Energy Levels are currently not a topical issue.

![image](https://cloud.githubusercontent.com/assets/4535772/22970712/2ff42b12-f3c7-11e6-94fb-61b982834769.png)

However if there is demand for more transparency I could wireup and pay for an AWS Lambda service to schedule a poll and data transform once a week, but only if this become topical again.
